// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Scan root directories for Git repositories and return their paths. */
	scanRepositories: (config: ScanConfig) => typedError<string[], string>(__TAURI_INVOKE("scan_repositories", { config })),
	/**  Get the full Git status for a single repository. */
	getRepoStatus: (path: string) => typedError<RepoStatus, string>(__TAURI_INVOKE("get_repo_status", { path })),
	/**  Get status for multiple repositories in parallel (bounded concurrency). */
	getReposStatus: (paths: string[]) => typedError<RepoStatus[], string>(__TAURI_INVOKE("get_repos_status", { paths })),
	/**  Run `git fetch` on multiple repos with concurrency limit, streaming progress via events. */
	fetchRepos: (paths: string[], concurrency: number | null) => typedError<null, string>(__TAURI_INVOKE("fetch_repos", { paths, concurrency })),
	/**  Run `git pull` on multiple repos with concurrency limit, streaming progress via events. */
	pullRepos: (paths: string[], concurrency: number | null) => typedError<null, string>(__TAURI_INVOKE("pull_repos", { paths, concurrency })),
	/**  Get all local branches for a repository. */
	getRepoBranches: (path: string) => typedError<string[], string>(__TAURI_INVOKE("get_repo_branches", { path })),
	/**  Safely check out a local branch. */
	checkoutBranch: (path: string, branchName: string) => typedError<null, string>(__TAURI_INVOKE("checkout_branch", { path, branchName })),
	/**  Get all changed files for a repository. */
	getChangedFiles: (path: string) => typedError<ChangedFile[], string>(__TAURI_INVOKE("get_changed_files", { path })),
	/**  Get unified diff for a single file. */
	getFileDiff: (repoPath: string, filePath: string, isStaged: boolean, isUntracked: boolean) => typedError<string, string>(__TAURI_INVOKE("get_file_diff", { repoPath, filePath, isStaged, isUntracked })),
	/**  Get all merge conflict files for a repository with their contents. */
	getMergeConflicts: (repoPath: string) => typedError<ConflictFile[], string>(__TAURI_INVOKE("get_merge_conflicts", { repoPath })),
	/**  Write resolution content to file and mark it as resolved (git add). */
	resolveConflict: (repoPath: string, filePath: string, content: string) => typedError<null, string>(__TAURI_INVOKE("resolve_conflict", { repoPath, filePath, content })),
	/**  Stash local uncommitted changes. */
	stashRepo: (path: string) => typedError<null, string>(__TAURI_INVOKE("stash_repo", { path })),
	/**  Commit staged changes and push to origin. */
	commitAndPush: (path: string, message: string) => typedError<null, string>(__TAURI_INVOKE("commit_and_push", { path, message })),
	/**  Verify if system Git CLI is available. Returns (available, version_string). */
	checkSystemGit: () => typedError<boolean, string>(__TAURI_INVOKE("check_system_git")),
	/**
	 *  Check if an SSH agent is running and has loaded keys.
	 *  Uses `ssh-add -l` which works on Linux, macOS, and Windows (OpenSSH ≥ Win10 1803).
	 *  Returns Ok(true) if agent is reachable, Ok(false) if not found or no keys.
	 */
	checkSshAgent: () => typedError<boolean, string>(__TAURI_INVOKE("check_ssh_agent")),
	/**  Log frontend React errors directly to a file for debugging */
	logFrontendError: (error: string, stack: string) => __TAURI_INVOKE<void>("log_frontend_error", { error, stack }),
};

/* Types */
/**  A changed file in a repository */
export type ChangedFile = {
	path: string,
	status: string,
};

/**  A file with conflicts and its Ours/Theirs/Base content */
export type ConflictFile = {
	path: string,
	our_content: string,
	their_content: string,
	base_content: string,
};

/**  Local file changes summary */
export type FileChanges = {
	staged: number,
	unstaged: number,
	untracked: number,
};

/**  Full status snapshot for a single repository */
export type RepoStatus = {
	path: string,
	name: string,
	branch: string,
	tracking_branch: string | null,
	ahead: number,
	behind: number,
	changes: FileChanges,
	last_commit_hash: string | null,
	last_commit_message: string | null,
	last_commit_author: string | null,
	last_commit_time: string | null,
	sync_status: SyncStatus,
	error_message: string | null,
};

/**  Scan configuration from frontend */
export type ScanConfig = {
	root_paths: string[],
	max_depth: number | null,
	exclude_patterns: string[] | null,
};

/**  Sync status of a repository relative to its remote tracking branch */
export type SyncStatus = 
/**  Local is in sync with remote */
"synced" | 
/**  Local has commits remote doesn't */
"ahead" | 
/**  Remote has commits local doesn't */
"behind" | 
/**  Both local and remote have diverged commits */
"diverged" | 
/**  Currently fetching/pulling */
"updating" | 
/**  Auth credentials required */
"auth_required" | 
/**  Operation failed */
"error" | 
/**  No remote tracking branch configured */
"no_remote" | 
/**  Repository not yet scanned */
"unknown";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

